# Generated by Django 5.2.4 on 2025-07-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_exerciselog_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.TextField(help_text='List or description of meals for the day')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.member')),
            ],
            options={
                'verbose_name': 'Food Plan',
                'verbose_name_plural': 'Food Plans',
                'ordering': ['-date'],
            },
        ),
    ]
