# Generated by Django 5.2.4 on 2025-07-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_foodplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='food_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.foodplan'),
        ),
    ]
