# Generated by Django 5.2.4 on 2025-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_foodlog_food_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodplan',
            old_name='meals',
            new_name='description',
        ),
    ]
